name: jetgp
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.9.*
  - numpy
  - scipy
  - cython=0.29.*
  - pandas
  - make
  - cmake
  - gcc
  - gfortran
  - ipykernel
  - conda-forge::pyvista
  - conda-forge::gmsh
  - conda-forge::python-gmsh
  - conda-forge::vtk
  - conda-forge::scikit-sparse
  - conda-forge::scikit-umfpack
  - ipython
  - jupyter_sphinx
  - sphinx >=7.1
  - sphinx-argparse
  - sphinx-book-theme
  - sphinx-copybutton >=0.5.1
  - sphinx-design
  - sphinx_rtd_theme >=3
  - sphinxcontrib-bibtex
  - numba
  - sympy
  - line_profiler
  - pip
  - pip:
    - torch
    - scikit-learn
    - pytest
    - pytest-cov